language: python

addons:
  apt:
    packages:
      - libgdal1h
      - gdal-bin
      - libgdal-dev
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
python:
  - "3.5"

install:
  - pip install -r other/requirements.txt
  - pip install pytest-django

script: "py.test ."
