language: python

env:
  - RASTERIO_VERSION=0.26.0

addons:
  apt:
    packages:
      - libgdal1h
      - gdal-bin
      - libgdal-dev
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
python:
  - "3.5"

cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/wheelhouse

before_install:
  - curl -L https://github.com/mapbox/rasterio/releases/download/$RASTERIO_VERSION/rasterio-travis-wheels-$TRAVIS_PYTHON_VERSION.tar.gz > /tmp/wheelhouse.tar.gz
  - tar -xzvf /tmp/wheelhouse.tar.gz -C $HOME

install:
  - pip install --install-option="--no-cython-compile" cython>=0.23.1
  - pip install -r other/requirements.txt --use-wheel --find-links=$HOME/wheelhouse --cache-dir $HOME/.pip-cache
  - pip install pytest-django

script: "py.test ."
